CREATE TABLE CUSTOMER
(
    `ID`      bigint NOT NULL AUTO_INCREMENT,
    `NAME`    varchar(255) DEFAULT NULL,
    `EMAIL`   varchar(255) DEFAULT NULL,
    `ADDRESS` varchar(255) DEFAULT NULL,
    PRIMARY KEY (`ID`)
);


CREATE TABLE BOOKING
(
    `ID`          BIGINT         NOT NULL AUTO_INCREMENT,
    `BOOKING_ID`  VARCHAR(36)    NOT NULL UNIQUE, -- The UUID from Java
    `CUSTOMER_ID` BIGINT,
    `EVENT_ID`    BIGINT         NOT NULL,
    `QUANTITY`    BIGINT         NOT NULL,
    `TOTAL_PRICE` DECIMAL(10, 2) NOT NULL,
    `STATUS`      VARCHAR(20)    NOT NULL DEFAULT 'PENDING',
    `PLACED_AT`   TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID`),
    CONSTRAINT `FK_BOOKING_CUSTOMER` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES CUSTOMER (`ID`) ON DELETE SET NULL
);