CREATE TABLE SEAT_ALLOCATIONS
(

    ID       BIGINT      NOT NULL AUTO_INCREMENT,
    EVENT_ID BIGINT,
    ORDER_ID VARCHAR(36) NOT NULL UNIQUE,
    QUANTITY BIGINT      NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    CONSTRAINT FK_EVENT_ID FOREIGN KEY (EVENT_ID) REFERENCES EVENT (ID) ON DELETE SET NULL

);