ALTER TABLE SEAT_ALLOCATIONS
    CHANGE COLUMN ORDER_ID BOOKING_ID VARCHAR(36) NOT NULL,
    ADD COLUMN STATUS VARCHAR(20) NOT NULL DEFAULT 'RESERVED' AFTER QUANTITY;

ALTER TABLE SEAT_ALLOCATIONS DROP INDEX ORDER_ID;
ALTER TABLE SEAT_ALLOCATIONS ADD UNIQUE KEY UK_BOOKING_ID (BOOKING_ID);