CREATE TABLE `ORDERS`
(
    `ID`             BIGINT         NOT NULL AUTO_INCREMENT,
    `ORDER_ID`       VARCHAR(36)    NOT NULL UNIQUE, -- The UUID TO SEND USER
    `BOOKING_ID`     VARCHAR(36)    NOT NULL UNIQUE, -- The UUID TO SEND USER
    `CUSTOMER_ID`    BIGINT   NOT NULL,
    `CUSTOMER_EMAIL` VARCHAR(255)  NOT NULL,
    `EVENT_ID`       BIGINT         NOT NULL,
    `VENUE_ID`       BIGINT         NOT NULL,
    `QUANTITY`       BIGINT         NOT NULL,
    `TOTAL_PRICE`    DECIMAL(10, 2) NOT NULL,
    `STATUS`         VARCHAR(20)    NOT NULL DEFAULT 'PROCESSING',
    `CREATED_AT`     TIMESTAMP               DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID`)
);