# =========================================================================
# DOCKER ENVIRONMENT OVERRIDES
# =========================================================================

# Override MySQL connection to point to the Docker container database service and port
spring.datasource.url=jdbc:mysql://booking-db:3306/INVENTORY_MANAGEMENT?allowPublicKeyRetrieval=true&useSSL=false

# Override Kafka connection to point to the internal broker container listener
spring.kafka.bootstrap-servers=kafka-broker:29092

