name: TicketBolt CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build Booking Service
        working-directory: ./booking-service
        run: mvn clean package -DskipTests

      - name: Build Inventory Service
        working-directory: ./inventory-service
        run: mvn clean package -DskipTests

      - name: Build Order Service
        working-directory: ./order-service
        run: mvn clean package -DskipTests